// Code generated by SalGen. DO NOT EDIT.
package actsal

import (
	"context"
	"database/sql"

	"github.com/go-gad/sal"
	"github.com/go-gad/sal/examples/bookstore1"
	"github.com/pkg/errors"
)

type StoreClientManager struct{}

func NewStoreClientManager() *StoreClientManager {
	return &StoreClientManager{}
}

func (m *StoreClientManager) Begin(s bookstore1.StoreClient) (bookstore1.StoreClient, error) {
	c := s.(*SalStoreClient)

	dbconn := c.DBH.(sal.TransactionBegin)

	tx, err := dbconn.Begin()
	if err != nil {
		return nil, errors.Wrap(err, "failed to start tx")
	}

	// todo: copy settings, middlewares, options...
	newss := NewStoreClient(tx)

	return newss, nil
}

func (m *StoreClientManager) Commit(ss bookstore1.StoreClient) error {
	c := ss.(*SalStoreClient)

	txconn := c.DBH.(sal.TransactionEnd)

	err := txconn.Commit()

	return errors.Wrap(err, "failed to commit")
}

func (m *StoreClientManager) Rollback(ss bookstore1.StoreClient) error {
	c := ss.(*SalStoreClient)

	txconn := c.DBH.(sal.TransactionEnd)

	err := txconn.Rollback()

	return errors.Wrap(err, "failed to commit")
}

type SalStoreClient struct {
	DBH sal.DBHandler
}

func NewStoreClient(dbh sal.DBHandler) *SalStoreClient {
	return &SalStoreClient{DBH: dbh}
}

func (s *SalStoreClient) CreateAuthor(ctx context.Context, req bookstore1.CreateAuthorReq) (*bookstore1.CreateAuthorResp, error) {
	var reqMap = make(sal.RowMap)
	reqMap["Name"] = &req.Name
	reqMap["Desc"] = &req.Desc

	pgQuery, args := sal.ProcessQueryAndArgs(req.Query(), reqMap)

	rows, err := s.DBH.Query(pgQuery, args...)
	if err != nil {
		return nil, errors.Wrap(err, "failed to execute Query")
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return nil, errors.Wrap(err, "failed to fetch columns")
	}

	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return nil, errors.Wrap(err, "rows error")
		}
		return nil, sql.ErrNoRows
	}

	var resp bookstore1.CreateAuthorResp
	var respMap = make(sal.RowMap)
	respMap["ID"] = &resp.ID
	respMap["CreatedAt"] = &resp.CreatedAt

	var dest = make([]interface{}, 0, len(respMap))
	for _, v := range cols {
		if intr, ok := respMap[v]; ok {
			dest = append(dest, intr)
		}
	}

	if err = rows.Scan(dest...); err != nil {
		return nil, errors.Wrap(err, "failed to scan row")
	}

	if err := rows.Err(); err != nil {
		return nil, errors.Wrap(err, "something failed during iteration")
	}

	return &resp, nil
}

func (s *SalStoreClient) GetAuthors(ctx context.Context, req bookstore1.GetAuthorsReq) ([]*bookstore1.GetAuthorsResp, error) {
	var reqMap = make(sal.RowMap)
	reqMap["id"] = &req.ID
	reqMap["tags"] = &req.Tags

	req.ProcessRow(reqMap)

	pgQuery, args := sal.ProcessQueryAndArgs(req.Query(), reqMap)

	rows, err := s.DBH.Query(pgQuery, args...)
	if err != nil {
		return nil, errors.Wrap(err, "failed to execute Query")
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return nil, errors.Wrap(err, "failed to fetch columns")
	}

	var list = make([]*bookstore1.GetAuthorsResp, 0)

	for rows.Next() {
		var resp bookstore1.GetAuthorsResp
		var respMap = make(sal.RowMap)
		respMap["id"] = &resp.ID
		respMap["created_at"] = &resp.CreatedAt
		respMap["name"] = &resp.Name
		respMap["desc"] = &resp.Desc
		respMap["tags"] = &resp.Tags

		resp.ProcessRow(respMap)

		var dest = make([]interface{}, 0, len(respMap))
		for _, v := range cols {
			if intr, ok := respMap[v]; ok {
				dest = append(dest, intr)
			}
		}

		if err = rows.Scan(dest...); err != nil {
			return nil, errors.Wrap(err, "failed to scan row")
		}

		list = append(list, &resp)
	}

	if err := rows.Err(); err != nil {
		return nil, errors.Wrap(err, "something failed during iteration")
	}

	return list, nil
}

func (s *SalStoreClient) UpdateAuthor(ctx context.Context, req *bookstore1.UpdateAuthorReq) error {
	var reqMap = make(sal.RowMap)
	reqMap["ID"] = &req.ID
	reqMap["Name"] = &req.Name
	reqMap["Desc"] = &req.Desc

	pgQuery, args := sal.ProcessQueryAndArgs(req.Query(), reqMap)

	_, err := s.DBH.Exec(pgQuery, args...)
	if err != nil {
		return errors.Wrap(err, "failed to execute Exec")
	}

	return nil
}
